  build_linux_aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build aarch64 wheel
        uses: docker://quay.io/pypa/manylinux_2_28_aarch64
        with:
          args: |
            bash -c "
            PYTHON=/opt/python/cp38-cp38/bin/python &&
            $PYTHON -m pip install --upgrade pip build wheel &&
            $PYTHON -m build --wheel &&
            mkdir -p /github/workspace/dist_aarch64 &&
            cp dist/*.whl /github/workspace/dist_aarch64/
            "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-aarch64-wheel
          path: dist_aarch64/*.whl